version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: thejerryuc123098
          # password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
          password: M,wUV7F?)qD.Z67
    steps:
      - checkout
      - run: ./mvn test

  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: thejerryuc123098
          password: M,wUV7F?)qD.Z67 # context / project UI env-var reference
    steps:
      - checkout
      - run: ./mvn -Dmaven.test.skip=true package

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
