name: CI Build Script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
   test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 1.18
      - name: Maven Build (Goal = package)
        run: mvn -B clean package -DskipTests
      - name: Unit Tests (Goal = Verify)
        run: mvn -B clean verify
